[[1月]]
products = ["かに", "おせち", "ふるさと納税", "スキーやスノーボード用具", "新春セール", "ダイエット関連商品", "寒冷地向け衣料品", "年末年始のセール", "家庭用暖房機器", "インフルエンザ予防商品"]

[[2月]]
products = ["バレンタインデー関連商品", "冬季セール", "スキーやスノーボード用具", "ひな祭り関連商品", "冬のアウトドア用品", "スーツ・ビジネスウェア", "冬季限定コスメ", "冬の旅行プラン", "バーゲンセール", "スキンケア商品"]

[[3月]]
products = ["桜の季節に関連した商品", "春服・春物アクセサリー", "卒業シーズンのギフト", "春のホームインテリア", "園芸用具・植物", "スポーツイベント関連商品", "春の新生活アイテム", "季節限定アイスクリーム", "春休み旅行プラン", "ファッションアクセサリー"]

[[4月]]
products = ["入学シーズンの教材・文房具", "春のファッションアイテム", "花見用品", "新生活家電", "スポーツ用品", "季節の食材・レシピ", "春の美容商品", "ゴールデンウィーク旅行予約", "スキンケア商品", "アウトドア用品"]

[[5月]]
products = ["ゴールデンウィーク特集", "旅行関連商品", "アウトドア用品", "マザーズデーのギフト", "ファッションアクセサリー", "新緑の季節に関連した商品", "ピクニック用品", "スポーツイベントチケット", "春のヘルシー食品", "花・観葉植物"]

[[6月]]
products = ["ランドセル", "ファーザーズデーのギフト", "サマーセール", "水着・ビーチウェア", "アイスクリーム・かき氷機", "屋外用家具", "夏季スポーツ用具", "キャンプ用品", "日焼け対策商品", "サマーフェスティバル用品"]

[[7月]]
products = ["夏季セール", "海水浴用品", "夏祭り関連商品", "冷たい飲料・ビール", "BBQグリル・アクセサリー", "屋外コンサートチケット", "蚊取り線香・虫除け商品", "水遊び用具", "ビーチタオル・浮き輪", "夏のファッションアイテム"]

[[8月]]
products = ["夏季限定フード・ドリンク", "夏休み旅行関連商品", "ビーチウェア", "プール用品", "キャンプ用品", "アイスクリームメーカー", "クーラーボックス", "サマーグリーティングカード", "日焼け止め・保湿剤", "サマーアクティビティ予約"]

[[9月]]
products = ["バック・リュックサック", "秋服・秋物アクセサリー", "教科書・学習教材", "秋の野菜・季節の食材", "スポーツシューズ", "秋のアウトドア用品", "ヘルシー食品", "秋の新商品発売", "ハロウィン衣装・デコレーション", "読書関連商品"]

[[10月]]
products = ["ハロウィン関連商品", "秋の行楽シーズンのアイテム", "スポーツ用品", "秋のホームインテリア", "秋のアウトドア活動", "秋のビューティープロダクト", "ハロウィンイベントチケット", "秋の旅行プラン", "季節限定フレーバー飲料", "秋のフェスティバル用品"]

[[11月]]
products = ["クリスマスプレゼント", "ブラックフライデーセール", "寒冷地向け衣料品", "秋冬アウトドア用品", "秋のフードトレンド", "感謝祭関連商品", "秋のワイン・洋酒", "ホリデーシーズンのイルミネーション", "冬のスポーツ用具", "温かいブランケット"]

[[12月]]
products = ["年末年始のおせち・お歳暮", "クリスマスケーキ", "冬季セール", "冬のアウトドア用品", "クリスマスツリー・デコレーション", "年末の旅行プラン", "寒冷地向け暖房機器", "忘年会・クリスマスパーティー用品", "冬のファッションアイテム", "新年のお祝い用品"]
