[prompt]
adjective = ["vibrant", "mysterious", "serene", "dynamic", "ethereal"]
noun = ["landscape", "cyberpunk city", "fantasy castle", "wildlife", "abstract art"]
action = ["unfolding", "emerging", "transforming", "shifting", "evolving"]
style = ["impressionist", "futuristic", "surreal", "minimalist", "neon"]
color = ["vivid", "monochrome", "pastel", "contrast", "harmony"]
emotion = ["awe", "wonder", "contemplation", "excitement", "tranquility"]

type = ["illustration", "photorealistic", "3dcg"]
time = ["retro", "youthful", "modern", "futuristic"]
composition = ["symmetrical"]
artist = ["Bancsy"]
style = ["oil painting", "watercolor painting", "comic book", "isometric", "low poly", "line art", "craft clay", "3d model", "pixel art"]
category = ["animal", "architecture"]
subject = ["long-hair girl", "20 years old Japanese", "3 grieving man", "leather jacket"]
character_status = ["moderate smiling", "full body", "upper body", "looking at viewer", "dutch angle", "low angle", "shiny skin", "detailed eyes", "flat chest", "indirect looking away", "indirect looking side eye contact", "formal outfit"]
character_layout = ["long shot layout"]
background = ["solid no background", "blurry", "milky way", "street snap", "under the-elevated-railway background", "indoor background", "cafe", "lakeside", "urban", "park"]
mood = []
situation = []
scene = ["sunny", "rainy", "cloudy", "morning", "night", "dawn", "sunset"]
camera = ["120mm lens", "f1.2 depth", "bird's eye view", "fisheye lens", "gopro", "macro lens", "daguerreotype", "satellite photo"]
lighting = ["natural light", "moon light", "indirect light", "neon light", "colorful light", "day light"]
quality_modifiers = ["masterpiece", "postprocessing", "4k", "hires", "cinematic", "best quality", "highly detailed", "beautiful composition"]
negative = ["easynegative", "ng_deepnegative_v1_75t", "nsfw", "nude", "nipples", "signature", "2d"]
aspect_ratio = ["512x512", "640x360", "360x640", "480x360", "600x400", "600x480", "640x480"]
